[pytest]
addopts = --strict-markers -ra --tracing=retain-on-failure --screenshot=only-on-failure
base_url = https://playwright.dev/python/
testpaths = tests
markers =
    smoke: Quick sanity tests for core functionality
    regression: Full deep-dive test suite